4월 5일
Altu-Bitu-2/ATBT pull request #7
Opened 2022-04-10 19:48 UTC by jhyii

내용 & 질문
2812번 문제를 로컬에서 돌렸을 땐 잘 나오는데 시간초과가 뜹니다. while문 있는 부분을 더 잘 수정할 수 있을 것 같은데 어떻게 할지 잘 모르겠습니다.
<기존 제출>
2437, 2812, 13305
<추가 제출>
X

2022-04-11 19:36 UTC, ZERO-black requested changes

2022-04-11 19:36 UTC, ZERO-black commented on 4월 5일 그리디알고리즘/13305.py
> +        price += min(stat[:i+1])*necess #필요한 가스 양만큼 앞의 주유소 중 가장 싼 곳에서 산 걸로 친다
p1. 리스트에서 min연산은 O(n)시간 복잡도를 가져요! 매번 이렇게 구하면 시간초과가 뜨겠죠?
이렇게 구하는 방법 말고, 현재까지 가장 싼 가격인 주유소 값을 저장할 수 있는 방법이 있지 않을까요?

2022-04-11 19:36 UTC, ZERO-black commented on 4월 5일 그리디알고리즘/2812.py
> +            del num[j]
p1. del 키워드를 통해 리스트 속 원소를 삭제할 경우, 해당 원소 **뒤에 있는 모든 원소들을 한칸씩 앞으로 당겨오는** 연산이 일어나게 됩니다. 따라서 시간복잡도가 O(n)이에요! 지울 때마다 일어나는 연산이니, 시간초과로 이어졌을거에요. 원소의 삭제가 O(1)이 되는 자료구조를 사용해야 할것 같아요!

<details>
<summary>힌트</summary>
이미 확정된 수만 가지고 생각해보세요! 삭제 연산은 항상 뒤에서만 일어나고 있어요! 이럴 때 어떤 자료구조를 쓰면 좋을까요?
</details>

2022-04-11 19:48 UTC, nanometre380 reviewed
- 코드리뷰가 겹쳐서 삭제합니다-

2022-04-11 19:48 UTC, nanometre380 commented on 4월 5일 그리디알고리즘/13305.py
> +        my_gas += necess #보유하는 가스 양이 산만큼 많아진다
P1. 여기서 내가 보유하고 있는 가스의 양을 따로 구할 필요가 없어요! 한칸 한칸 전진하며 남는 가스 양을 체크하여 기름을 채우는 방법보단, 단순히 도시를 이동하는 데 드는 기름을 지금까지 중 최저가로 산다면, 가장 싼 곳에서 최대한 많이 사서 최소 비용이 구해지지 않을까요? min()을 사용하는 것이 아니라, 지금까지의 최저가와 다음 도시의 기름값을 비교하여 최저가를 계속 저장하고 있어야 해요! 
+ 현재 주유소 문제가 백준 정답처리가 안 되어 있어요. 그래서 다시 풀어보시길 바라며 P1 태그 드렸습니다. 추가 제출이 아닌 경우 정답 처리가 되어야 과제 제출로 인정이 되니 확인해주세요!

2022-04-11 19:48 UTC, nanometre380 commented on 4월 5일 그리디알고리즘/2437.py
> +        break
어차피 리스트의 인덱스를 참조하여 사용하고 있으니 ` for i in range(n)` 보다는 `for w in chu` 이런 식으로 사용하는 것이 좋을 것 같아요! 풀이는 깔끔합니다 👍

2022-04-11 19:48 UTC, nanometre380 commented on 4월 5일 그리디알고리즘/2812.py
> +            break
P1. 생각하신 방법 자체가 아예 틀린 것으로 보이진 않지만, 이러한 방법을 사용한 더 좋은 풀이를 생각하셔야 할 것 같습니다! 가장 앞자리가 될 수의 인덱스를 찾고, 거기에 맞춰 앞자리가 뒷자리 숫자보다 작을 때 앞자리 숫자를 지우고 계신데, 제일 큰 숫자를 미리 찾아 놓는 방법밖에 없을까요? 이번 과제는 그리디 알고리즘 과제이고, 그리디 알고리즘의 현재 상황에서 최선의 선택을 하여 최종적으로도 최선의 선택을 만드는 것입니다. 그럼 가장 먼저 큰 숫자를 찾을 필요 없이 n-k 자리 숫자를 만들기 위한 변수를 만들어 놓고, 입력받은 수의 각 자리 숫자를 돌며 그 때의 최적의 숫자를 찾아놓으면 되지 않을까요? 또한, del의 시간 복잡도는 O(n)이므로 효율적인 방법이 아닙니다. 앞자리의 숫자를 편하게 지우려면... stack의 pop을 사용할 수 있을 것 같지 않나요?
따라서 문제를 재풀이하셔야 할 것 같아요! 그리디 알고리즘 풀이 방법을 고민해보시면 좋겠습니다!

2022-04-11 19:59 UTC, ZERO-black reviewed
두 문제는 백준 기준 정답이 뜨지 않았기 때문에 선택 1/5문제 확인되셨습니다!
p1 태그 받으신 두 문제 수정하시고 저 다시 리뷰어로 호출해주세요😊

2022-04-11 19:59 UTC, ZERO-black commented on 4월 5일 그리디알고리즘/2437.py
> +chu = list(map(int, input().split()))
p3. 변수명은 명확하게 설정해야 해요! 코드의 가독성과 이어지는 부분이니까, 코딩테스트 같이 시간이 없을 때는 어쩔 수 없지만 평소에는 명확하게 짓도록 연습하는 것을 추천드립니다😊

2022-04-11 19:59 UTC, ZERO-black commented on 4월 5일 그리디알고리즘/2437.py
> +        result += chu[i] #추의 무게가 여태까지 추의 합+1보디 작거나 같다면 앞의 조합들로 구할 수 있음
p3. 반복문 내에서 i를 따로 사용하지 않는 경우에는, `for i in chu`와 같이 써주시면 값을 바로 참조 할 수 있어서 코드를 더 간결하게 쓸 수 있습니다!

2022-04-14 13:58 UTC, ZERO-black commented
3/5문제 확인되셨습니다! 편하게 머지하셔도 돼요!

2022-04-29 17:15 UTC, merged